[libdefaults]
  default_realm = GO01-DEM.YLCU-ATMI.CLOUDERA.SITE
  dns_lookup_realm = true
  dns_lookup_kdc = true
  ticket_lifetime = 24h
  renew_lifetime = 7d
  forwardable = true
  rdns = false
  udp_preference_limit = 1

[realms]
  GO01-DEM.YLCU-ATMI.CLOUDERA.SITE = {
  }

[domain_realm]
  .go01-dem.ylcu-atmi.cloudera.site = GO01-DEM.YLCU-ATMI.CLOUDERA.SITE
  go01-dem.ylcu-atmi.cloudera.site = GO01-DEM.YLCU-ATMI.CLOUDERA.SITE
  .ylcu-atmi.cloudera.site = GO01-DEM.YLCU-ATMI.CLOUDERA.SITE
  ylcu-atmi.cloudera.site = GO01-DEM.YLCU-ATMI.CLOUDERA.SITE
